version: '3'

services:
  gaussian-splatting:
    build:
      context: ../Dockerfile/gaussian-splatting
      dockerfile: Dockerfile
    image: 3dgs
    container_name: 3dgs
    volumes:
      - ../datasets:/workspace/gaussian-splatting/datasets
      - ../output:/workspace/gaussian-splatting/output
    working_dir: /workspace/gaussian-splatting
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  super-splat:
    build:
      context: ../Dockerfile/super-splat
      dockerfile: Dockerfile
    image: super-splat:v1.6.0
    container_name: super-splat
    working_dir: /workspace/super-splat
    tty: true
    ports:
      - 3000:3000

  nerfstudio:
    build:
      context: ../Dockerfile/nerfstudio
      dockerfile: Dockerfile
    image: nerfstudio:gaussian-splatting
    container_name: nerfstudio
    working_dir: /workspace/nerfstudio
    volumes:
      - ../output:/workspace/output
    tty: true
    ports:
      - 7007:7007
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
